# Generated by Django 5.0.2 on 2024-03-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_blog_created_at_blog_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="blog",
            name="image_file",
            field=models.ImageField(
                blank=True, default="default.jpg", upload_to="images/"
            ),
        ),
    ]
