version: '3'

services:
  django_app:
    build: .
    env_file:
      - .env
    volumes:
      - static_vol_django:/app/connectjcuServer/static
      - media_vol_django:/app/connectjcuServer/media
    ports:
      - 8000:8000

  nginx:
    build: ./nginx
    volumes:
      - static_vol_nginx:/app/connectjcuServer/static
      - media_vol_nginx:/app/connectjcuServer/media
    ports:
      - 80:80
      - 443:443
    depends_on:
      - django_app

volumes:
  static_vol_django:
  media_vol_django:
  static_vol_nginx:
  media_vol_nginx: