# Generated by Django 5.0.2 on 2024-03-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_onetimepassword"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True, default="default.jpg", upload_to="images/"
            ),
        ),
    ]
