# Generated by Django 5.0.2 on 2024-04-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="article_author",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
